### ISSUE TITLE
Seperate Docker Image

### ISSUE THREAD

**Issue by kfoxton** [varun-raj/immich-power-tools#10]
I created an Unraid deployment for this, and the UI loads up, but no images load.  The Web ui reports "Request failed with status code 500" .

In the docker logs I get this error as well:

 ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production

The UI is able to see the album titles in my Immich deployment, but no images, exif data, etc.

Any ideas?

**Comment by varun-raj** [comment]
Hey @kfoxton,

I've removed the NextJS's image optimization to solve this, can you try the latest release and let me know?

**Comment by Beersteddy** [comment]
> I created an Unraid deployment for this, and the UI loads up, but no images load. The Web ui reports "Request failed with status code 500" .
> 
> In the docker logs I get this error as well:
> 
> ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
> 
> The UI is able to see the album titles in my Immich deployment, but no images, exif data, etc.
> 
> Any ideas?


Variable `IMMICH_URL` needs to have a port as well:
e.g.
`http://192.168.1.1:46642`

Unfortunately custom network trick does not work http://CONTAINER_NAME:PORT

**Comment by Beersteddy** [comment]
> Hey @kfoxton,
> 
> I've removed the NextJS's image optimization to solve this, can you try the latest release and let me know?

Current version as of today works just fine on unraid

**Comment by Tyree** [comment]
I set it up on unraid 2 days ago with zero issues. Spun right up and linked to immich and database without a single problem.
I have immich behind a reverse proxy with my router's DNS pointing the address back to the reverse proxy. So I used the full domain address for immich rather than IP and port.
I'm also using the imagegenius AIO container for immich (that is available via community apps). That may have simplified the setup some for me versus what you may have going on. Though it sounds like your issue may be with next js alone.

**Comment by kfoxton** [comment]
The Sharp issue is gone, but I am still getting the 500 error in the web UI. May be related to not running it as part of the Immich stack, since I am running it as a completely seperate docker?

`docker create
  --name='immich-power-tools'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="immich-power-tools"
  -e 'IMMICH_URL'='http://192.168.1.210:8080'
  -e 'IMMICH_API_KEY'='<REMOVED>'
  -e 'DATABASE_URL'='postgresql://<removed>:<removed>@192.168.1.210:5433'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8001]'
  -p '8001:3000/tcp' 'ghcr.io/varun-raj/immich-power-tools:latest'`

![image](https://github.com/user-attachments/assets/1d016bfd-3e4c-43df-b46d-13d1d976a3c2)

**Comment by Tyree** [comment]
Just making sure, is 8080 the correct host side port versus the container side port?
I know 8080 is the default port for immich, just making sure you did leave it as default on the host port.

**Comment by kfoxton** [comment]
Yep,

8080 is correct. The Url loads the immich url.

**Comment by Tyree** [comment]
I switched my container over to use the IP:Port as you're doing to see if that breaks it, but it still works.
Are you certain that your API key is correct? Can you try generating a new one and give that a try.
The last difference between my setup and yours is you are using bridge and I have immich and IMPT on the same docker network instead. Not sure if that would change anything being that neither of us is referencing the containers by name.

I'm not sure how you're getting the docker create command out of dockerman, but here is the XML for my template:
```
<?xml version="1.0"?>
<Container version="2">
  <Name>immich-power-tools</Name>
  <Repository>ghcr.io/varun-raj/immich-power-tools:latest</Repository>
  <Registry>https://github.com/varun-raj/immich-power-tools</Registry>
  <Network>proxynet</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support/>
  <Project/>
  <Overview/>
  <Category/>
  <WebUI>http://[IP]:[PORT:3000]</WebUI>
  <TemplateURL/>
  <Icon>https://raw.githubusercontent.com/varun-raj/immich-power-tools/main/public/favicon.png</Icon>
  <ExtraParams/>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1724669623</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="WebUI Port" Target="3000" Default="8010" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">8010</Config>
  <Config Name="IMMICH_URL" Target="IMMICH_URL" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">http://192.168.75.10:8091</Config>
  <Config Name="IMMICH_API_KEY" Target="IMMICH_API_KEY" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">--REDACTED--</Config>
  <Config Name="DB_USERNAME" Target="DB_USERNAME" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">--REDACTED--</Config>
  <Config Name="DB_PASSWORD" Target="DB_PASSWORD" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">--REDACTED--</Config>
  <Config Name="DB_HOST" Target="DB_HOST" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">postgresql14</Config>
  <Config Name="DB_PORT" Target="DB_PORT" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">5432</Config>
  <Config Name="DB_DATABASE_NAME" Target="DB_DATABASE_NAME" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">immich</Config>
  <Config Name="TZ" Target="TZ" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">America/New_York</Config>
</Container>
```

**Comment by kfoxton** [comment]
@Tyree Thanks for assisting! From reviewing your setup, I changed my connection to have the seperate DB connection information, instead of in a single connection string, and that seems to have resolved the issue!
