### ISSUE TITLE
Suggestion - Keep featured photo when merging

### ISSUE THREAD

**Issue by Tyree** [varun-raj/immich-power-tools#15]
Got this set up in minutes on unRAID. Very nice. Looking forward to seeing what you do with it!
One suggestion as I merge people is that the unknown person image ends up taking place of the featured photo I had already chosen for that person. Not sure how easy that is to fix.
Thanks!

**Comment by varun-raj** [comment]
Hi @Tyree,

Thanks for your comment <3 

Sure let me see how to achieve the that. I already got an option of whom we're should merge a bunch people into. Can you try that and let me know if it worked?

<img width="538" alt="image" src="https://github.com/user-attachments/assets/4b8d5591-6b53-4061-9db0-5bd1e92da608">

**Comment by Tyree** [comment]
Yes sir. I was using that feature (very nice). But it still picks another photo. When there's more than two, I'm not sure how it determines which photo to use. But it if the 5 or so times I tried it, it changed the photo every time. 
I ended up just clicking the link to go to the immich interface to do the merge. But then I didn't get the option to merge several faces at once like on IPT.
I think you're on to some great features here. I feel sure Alex and the crew would be very excited about this project if they don't already know about it.

**Comment by DanGarion** [comment]
From what I can tell this is similar to what Immich itself does when you move mismatched photos to the right person.

**Comment by Tyree** [comment]
> From what I can tell this is similar to what Immich itself does when you move mismatched photos to the right person.

Similar, but faster in that you can merge multiple faces at once.
But you're right, at the moment I am still using the direct Immich method since I can choose which direction the merge should happen AND keep the featured image. Although IPT also lets me choose the person the faces are merged into, for some reason the featured image setting is lost.

**Comment by DanGarion** [comment]
Sorry, I meant he issue you are having is similar (My experience on how this worksin Immich itself is the following. I have 2 People, Person A, and Person B. I go and review Person B and I see photos that are not their photos. I choose the photos and then choose Fix Incorrect Match, I then locate Person A, and select them. Immich then changes the Selected feautre photo of Person A), not the app. This app makes it so much easier.

**Comment by Tyree** [comment]
Ahh okay. I gotcha. I have not had to do the workflow you mention yet. I have merged lots of faces on immich (which works correctly, though I prefer the experience from the individual person page versus from the people page), but I have not yet fixed an incorrect match. 
I assume you have already posted an issue for this on immich GitHub.

**Comment by DanGarion** [comment]
No, and I'm sorry to hijack your issue... :) right now I'm trying to determine if it is a bug. Waiting to get feedback from others.

**Comment by Tyree** [comment]
No worries. Whether a bug or not, it can't be intended behavior. I woukd think named faces with featured photos should always take precedence over new assets added to that person. Similar to an album. If I add a photo to it, I don't want the cover photo changed every time. That's down right counterproductive! 😄

**Comment by varun-raj** [comment]
Hey Guys, 

Yeah I actually do it based on the selected person from the drop down, but it seems like immich itself has some issues related to this.

Adding the references here: 

https://github.com/immich-app/immich/issues/6382
https://github.com/immich-app/immich/issues/8335

**Comment by Tyree** [comment]
Gotcha. Interesting that they nailed it when done from the individual person page, but broken elsewhere. 
Hopefully they'll get it fixed soon.
Thanks!

**Comment by varun-raj** [comment]
Yeah, hoping so! I'll close this thread and we can revisit once its fixed in their side.

**Comment by kjack9** [comment]
FYI - I know both of those issues are closed, but this still seems to happen. If I merge with IPT, the featured photo for the destination person is being overwritten by one of the people I merged in. It's not a deal-breaker by any means, but it is annoying to have to reset constantly!

Great tool, thank you for it.
