### ISSUE TITLE
Feature Request: Add environment variable for public url

### ISSUE THREAD

**Issue by klejejs** [varun-raj/immich-power-tools#26]
Currently, the service connects to Immich through local Docker URL which looks like this: `http://immich_server:3001`. Unfortunately, the same URL is used in links to redirect to Immich URLs.
It would be nice if I could set my custom public Immich URL to be used in those links.

**Comment by klejejs** [comment]
Looks related to https://github.com/varun-raj/immich-power-tools/pull/25

**Comment by sai80082** [comment]
Hey yeah will be fixed soon we are fixing few more bugs and then will release a new one.

**Comment by sai80082** [comment]
Hey ,there is a new release now you can set `EXTERNAL_IMMICH_URL` in .env file  which should redirect you properly.
example:
`
EXTERNAL_IMMICH_URL = "https://your-address"`

**Comment by klejejs** [comment]
Thanks! Works great!
