### ISSUE TITLE
Error using new docker image

### ISSUE THREAD

**Issue by hjspencer** [varun-raj/immich-power-tools#4]
Hi, I've just tried pulling the new docker image using the docker_compose.yml and it's failing with an "Internal Server Error" where as the docker image with dockerfile worked fine.

The logs from the docker host are

immich_power_tools  |   ▲ Next.js 14.2.5
immich_power_tools  |   - Local:        http://439b8231c6c7:3000
immich_power_tools  |   - Network:      http://172.29.8.2:3000
immich_power_tools  | 
immich_power_tools  |  ✓ Starting...
immich_power_tools  |  ✓ Ready in 270ms
immich_power_tools  | App -> pageProps {
immich_power_tools  |   props: { immichURL: undefined },
immich_power_tools  |   router: e0 {
immich_power_tools  |     route: '/',
immich_power_tools  |     pathname: '/',
immich_power_tools  |     query: {},
immich_power_tools  |     asPath: '/',
immich_power_tools  |     isFallback: false,
immich_power_tools  |     basePath: '',
immich_power_tools  |     locale: undefined,
immich_power_tools  |     locales: undefined,
immich_power_tools  |     defaultLocale: undefined,
immich_power_tools  |     isReady: true,
immich_power_tools  |     domainLocales: undefined,
immich_power_tools  |     isPreview: false,
immich_power_tools  |     isLocaleDomain: false
immich_power_tools  |   }
immich_power_tools  | }
immich_power_tools  | TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.
immich_power_tools  |     at o (/app/.next/server/chunks/9.js:31:66121)
immich_power_tools  |     at l (/app/.next/server/chunks/9.js:31:66810)
immich_power_tools  |     at f (/app/.next/server/chunks/9.js:31:15660)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11139
immich_power_tools  |     at Object.Kc [as useMemo] (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
immich_power_tools  |     at exports.useMemo (/app/node_modules/react/cjs/react.production.min.js:26:48)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11055
immich_power_tools  |     at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
immich_power_tools  |     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
immich_power_tools  |     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
immich_power_tools  |  ⨯ TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.
immich_power_tools  |     at o (/app/.next/server/chunks/9.js:31:66121)
immich_power_tools  |     at l (/app/.next/server/chunks/9.js:31:66810)
immich_power_tools  |     at f (/app/.next/server/chunks/9.js:31:15660)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11139
immich_power_tools  |     at Object.Kc [as useMemo] (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
immich_power_tools  |     at exports.useMemo (/app/node_modules/react/cjs/react.production.min.js:26:48)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11055
immich_power_tools  |     at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
immich_power_tools  |     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
immich_power_tools  |     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
immich_power_tools  | App -> pageProps {
immich_power_tools  |   props: { immichURL: undefined },
immich_power_tools  |   router: e0 {
immich_power_tools  |     route: '/_error',
immich_power_tools  |     pathname: '/_error',
immich_power_tools  |     query: {},
immich_power_tools  |     asPath: '/',
immich_power_tools  |     isFallback: false,
immich_power_tools  |     basePath: '',
immich_power_tools  |     locale: undefined,
immich_power_tools  |     locales: undefined,
immich_power_tools  |     defaultLocale: undefined,
immich_power_tools  |     isReady: true,
immich_power_tools  |     domainLocales: undefined,
immich_power_tools  |     isPreview: false,
immich_power_tools  |     isLocaleDomain: false
immich_power_tools  |   }
immich_power_tools  | }
immich_power_tools  | TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.
immich_power_tools  |     at o (/app/.next/server/chunks/9.js:31:66121)
immich_power_tools  |     at l (/app/.next/server/chunks/9.js:31:66810)
immich_power_tools  |     at f (/app/.next/server/chunks/9.js:31:15660)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11139
immich_power_tools  |     at Object.Kc [as useMemo] (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
immich_power_tools  |     at exports.useMemo (/app/node_modules/react/cjs/react.production.min.js:26:48)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11055
immich_power_tools  |     at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
immich_power_tools  |     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
immich_power_tools  |     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
immich_power_tools  |  ⨯ TypeError: Cannot destructure property 'auth' of 'e' as it is undefined.
immich_power_tools  |     at o (/app/.next/server/chunks/9.js:31:66121)
immich_power_tools  |     at l (/app/.next/server/chunks/9.js:31:66810)
immich_power_tools  |     at f (/app/.next/server/chunks/9.js:31:15660)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11139
immich_power_tools  |     at Object.Kc [as useMemo] (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
immich_power_tools  |     at exports.useMemo (/app/node_modules/react/cjs/react.production.min.js:26:48)
immich_power_tools  |     at /app/.next/server/chunks/9.js:31:11055
immich_power_tools  |     at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
immich_power_tools  |     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
immich_power_tools  |     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

**Comment by sai80082** [comment]
Which version were you using?

**Comment by hjspencer** [comment]
Was pulling the latest image but I think you've just updated it and I'm getting the same pulling v0.1.5

**Comment by hjspencer** [comment]
I've tried deploying this in the main immich docker_compose file and on it's own and I'm still getting the following error

> TypeError: Cannot destructure property 'auth' of 'e' as it is undefined

**Comment by hjspencer** [comment]
The error is there in the v0.1.6
Regards

**Comment by sai80082** [comment]
Hey i was not able to reproduce the error can you post your compose file here?

**Comment by hjspencer** [comment]
version: "3.8"
services:
  immich_power_tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - 3000:3000
    env_file:
      - .env

The .env is 
NEXT_PUBLIC_IMMICH_URL="http://<IPAddressOfImmichServer:2283/photos"
IMMICH_API_KEY="<APIKey>"
DATABASE_URL=""

**Comment by sai80082** [comment]
In .env
It should be `IMMICH_URL`
And the power-tools should be in the same compose file as immich.
See the sample [docker-compose-all-immich.yml](https://raw.githubusercontent.com/varun-raj/immich-power-tools/main/docker-compose-all-immich.yml) file for reference.

**Comment by DanGarion** [comment]
> And the power-tools should be in the same compose file as immich.

You are proposing that we add this to the all in one compose?

**Comment by DanGarion** [comment]
Just an FYI, I added it to my whole compose file for immich and I still get the same error.

**Comment by hjspencer** [comment]
> In .env It should be `IMMICH_URL` And the power-tools should be in the same compose file as immich. See the sample [docker-compose-all-immich.yml](https://raw.githubusercontent.com/varun-raj/immich-power-tools/main/docker-compose-all-immich.yml) file for reference.

What a dufus. I never saw that the .env was updated. I was just copying it from the older pre docker image build.
It's sorted
Thanks
