### ISSUE TITLE
Error message:ERR_BAD_RESPONSE

### ISSUE THREAD

**Issue by pyccl** [varun-raj/immich-power-tools#42]
I don't know which one the internal address and external address respectively refer to. I installed Docker Desktop on Windows 11, is the internal address of Docker? Or is it my Windows 11 address? Is the external address an Internet address or my Windows 11 address? I have no connection to the Internet for the time being. Conduct testing within the local area network. I use my own computer http://127.0.0.1:8001 It can be accessed normally, but when using the Windows 11 address on computers within the local area network or on my own computer, it prompts: "ERR_SAD-REPONSE".

![image](https://github.com/user-attachments/assets/67af5fc0-da4e-4b06-bf9a-2b7af3b73870)

**Comment by murraydb** [comment]
I'm getting a similar error. 
Deployed on Linux in same stack as immich
If I include the api key in the .env everything works, but if I try to use the new auth method I get this response.  Haven't had much time to troubleshoot So didn't want to open my own issue.

**Comment by sai80082** [comment]
Hey new auth has some issues we need to address.please use api key for now will update when the bugs are fixed.

**Comment by pyccl** [comment]
> Hey new auth has some issues we need to address.please use api key for now will update when the bugs are fixed.

oh,thinks.

I don't know which one the internal address and external address respectively refer to.please tell me.thinks.

**Comment by sai80082** [comment]
Internal address is the ip address of your machine (in your case its your win 11 address) and external is an internet address, if you don't have an external address you can leave it empty or can use the same internal address here.

**Comment by pyccl** [comment]
thinks.

**Comment by pyccl** [comment]
> Internal address is the ip address of your machine (in your case its your win 11 address) and external is an internet address, if you don't have an external address you can leave it empty or can use the same internal address here.

thinks.  I have some other suggestions, BUGs. Can you feedback together? Or a question an issuse?

**Comment by varun-raj** [comment]
Hey Everyone, Sorry there was an issue with cookie policy which lead to this error. 

Here is the PR : https://github.com/varun-raj/immich-power-tools/pull/43

**Comment by mariosemes** [comment]
I'm getting the same error. Running on Linux, Docker. In a stack with a fully working Immich instance.

This is the log I'm getting:
` ⨯ Error: getaddrinfo ENOTFOUND immich_postgres
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'immich_postgres'
}`

Not sure if it's searching for postgres instance inside the stack? where my postgres hostname is immich-postgres with a '-' and not a '_'

**Comment by mariosemes** [comment]
> I'm getting the same error. Running on Linux, Docker. In a stack with a fully working Immich instance.
> 
> This is the log I'm getting: ` ⨯ Error: getaddrinfo ENOTFOUND immich_postgres at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'immich_postgres' }`
> 
> Not sure if it's searching for postgres instance inside the stack? where my postgres hostname is immich-postgres with a '-' and not a '_'

Changed my docker compose file to match this '-' instead of '_'

Now I'm getting this error:
` ⨯ error: password authentication failed for user "undefined"
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 105,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '335',
  routine: 'auth_failed'
}`

Am I missing something? Using API key, no auth added to env?

**Comment by causefx** [comment]
> > I'm getting the same error. Running on Linux, Docker. In a stack with a fully working Immich instance.
> > This is the log I'm getting: ` ⨯ Error: getaddrinfo ENOTFOUND immich_postgres at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'immich_postgres' }`
> > Not sure if it's searching for postgres instance inside the stack? where my postgres hostname is immich-postgres with a '-' and not a '_'
> 
> Changed my docker compose file to match this '_' instead of '-'
> 
> Now I'm getting this error: ` ⨯ error: password authentication failed for user "undefined" at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:283:98) at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29) at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38) at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42) at Socket.emit (node:events:517:28) at addChunk (node:internal/streams/readable:368:12) at readableAddChunk (node:internal/streams/readable:341:9) at Readable.push (node:internal/streams/readable:278:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23) { length: 105, severity: 'FATAL', code: '28P01', detail: undefined, hint: undefined, position: undefined, internalPosition: undefined, internalQuery: undefined, where: undefined, schema: undefined, table: undefined, column: undefined, dataType: undefined, constraint: undefined, file: 'auth.c', line: '335', routine: 'auth_failed' }`
> 
> Am I missing something? I'm using API key, no auth or anything else.

set these ENV's

```
            - DB_USERNAME=${IMMICH_DB_USERNAME} # Postgress Database Username
            - DB_PASSWORD=${IMMICH_DB_PASSWORD} # Postgres Database Password
            - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME} # Name of the database 
```
