### ISSUE TITLE
In the "Manage People" page, sometimes there may be situations where thumbnails are not displayed. It will take a long time to come out.

### ISSUE THREAD

**Issue by pyccl** [varun-raj/immich-power-tools#46]
In the "Manage People" page, sometimes there may be situations where thumbnails are not displayed. It will take a long time to come out.

![image](https://github.com/user-attachments/assets/7b683a09-55b0-4ed1-9c60-fe62a5938feb)

**Comment by markmghali** [comment]
how did you fix this? I am having this issue 
![image](https://github.com/user-attachments/assets/98afe675-12e1-4c9d-bbea-b87fa1692f6c)
