### ISSUE TITLE
Feature Request: a way to filter images with no geolocation data, and a way to update it

### ISSUE THREAD

**Issue by BernardoGiordano** [varun-raj/immich-power-tools#69]
Right now on immich it is impossible to check if images have geolocation data attached to them without opening them one by one. It would be awesome to be able to handle them in a more efficient way somehow.

**Comment by varun-raj** [comment]
@BernardoGiordano We already have this, you can try the "Missing location" option in the sidebar for this

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/62426166-6315-44e9-938b-b918e1aa6eb4">

**Comment by BernardoGiordano** [comment]
Oh that's cool! Trying it out later today. I didn't see it mentioned in the README, that's why I opened this issue. Maybe it can be added so people who didn't try this yet are aware of the feature being already available

**Comment by varun-raj** [comment]
@BernardoGiordano Sure thing, I will update it and close this task

**Comment by BernardoGiordano** [comment]
Taking advantage to reply to this issue, since now I'm able to test this feature out (was waiting for ARM support). Looks like that the orphan asset count is broken (check the screenshot for 5th May 2018 attached below)

![immagine](https://github.com/user-attachments/assets/a6b938b6-180a-4194-b2b9-dcd538835e97)
