### ISSUE TITLE
Internal Server Error (fetch failed) even though I set everything up correctly

### ISSUE THREAD

**Issue by driftywinds** [varun-raj/immich-power-tools#77]
Hello, I setup everything correctly according to the docker compose method in the README and this is what it shows me (domain blacked out for security): -
![Screenshot 2024-12-02 105812](https://github.com/user-attachments/assets/5b0b9488-bd14-4d00-b24e-7bc2207e45ac)

What do I need to change to fix this? docker logs show this: - 
```
  ▲ Next.js 14.2.5
  - Local:        http://704976f07de4:3000
  - Network:      http://172.18.0.3:3000

 ✓ Starting...
 ✓ Ready in 435ms
```
.env file looks like this: - 
```
IMMICH_API_KEY= <my api key> # your_immich_api_key
IMMICH_URL = "http://localhost:2283" # Your immich instace ip address and port
EXTERNAL_IMMICH_URL = "<my external URL>" # External address of immich
```

**Comment by driftywinds** [comment]
For some reason, changing the API key to a new one did the trick??!

**Comment by RenaKunisaki** [comment]
I ran into this, and resolved it by changing the internal URL from localhost:2283 to myhostname.lan:2283.

**Comment by MochaSteve256** [comment]
> I ran into this, and resolved it by changing the internal URL from localhost:2283 to myhostname.lan:2283.

Same here, but solved it by changing `myhostname:2283` to `myhostname.local:2283`. (which is kinda weird because my server is accessible at `myhostname` everywhere else)

**Comment by hulmgulm** [comment]
To fix this issue, I had to replace the internal immich hostname with its ipv4 address. Changed
IMMICH_URL = "http://myimmichhost:2283"
to
IMMICH_URL = "http://192168.0.123:2283"

**Comment by neilhawkins** [comment]
If you are using the docker compose setup, it'll be related to how Docker handles networking.`localhost` won't resolve correctly between containers. If you use the Docker service name for the server then it'll work. The default is `immich-server`. e.g.

```env
IMMICH_URL=http://immich-server:2283
```

Official Docker [networking docs explain this](https://docs.docker.com/compose/how-tos/networking) in a bit more detail for those interested.

**Comment by hulmgulm** [comment]
> If you are using the docker compose setup, it'll be related to how Docker handles networking.`localhost` won't resolve correctly between containers. If you use the Docker service name for the server then it'll work. The default is `immich-server`. e.g.
> 
> ```dotenv
> IMMICH_URL=http://immich-server:2283
> ```
> 
> Official Docker [networking docs explain this](https://docs.docker.com/compose/how-tos/networking) in a bit more detail for those interested.

Good point. Haven't thought about this. Works very well!
