### ISSUE TITLE
not a bug but notice

### ISSUE THREAD

**Issue by aviv926** [varun-raj/immich-power-tools#9]
This looks like a great side project!
Regarding the latest release:

> Max Asset Count:
> Imagine you’re in the game of hiding off unwanted or random people’s face but you don’t know how to find it quickly, then its a nightmare mainly when you’ve case like me of 10,000 images.
> 
> To solve this I brought in Max Asset Count where you can filter faces that are only in 5-10 photos and you know they are mostly not so close people whom you can ignore and hide.

In Immich the person can be defined as a core type person so that if he is not in the defined range he will not even appear in "people" (yes this has a disadvantage, it does not put him in the hidden but simply does not show him - at all)

You can find this setting under [Minimum recognized faces](https://my.immich.app/admin/system-settings?isOpen=machine-learning+facial-recognition)

**Comment by varun-raj** [comment]
Hi @aviv926,

Thanks for sharing this info 🙏 , I didnt know this existed and thanks for the heads up. I'll update the read me accordingly and will close this.

**Comment by varun-raj** [comment]
Updated the release note 👍 🥳
